language: java

jdk:
- oraclejdk8

cache:
  directories:
  - "$HOME/.m2/repository"

env:
  global:
  - secure: PCr4uarWSl/+cuWxVlVneye580eIc8NTAHTY+ey4mjgF3RhfIfEzRIOtqYvOMk6bX4+A4molcOtL5Z3xHxjmrFIBHvT94mQfbYdoIkO16WFlp0P8nN95UG1fXRI4PNGT3txF9NbKzOzoejq1uLE2qEPDOC5yvQ8VYlEnmMIv7G/geCSKt0Oqr6MYVUKaIJFXY5m8zh9K8F/W70/RHDS4h3lYcE2dRR97zG6nwYt++yosKflROWs7pBUWvMLt038pkffAltUItmdNn88SEBdJ1bT0GogQuz3yT1nlMH8cyIpvjd0r9hhh7jdPieebWncuSmnI92AgqqRSbjY+l0opQ9mvnuL1t6QGd1Lq1DdBBzd/Kv5zLp9ZNJzJDn9ZaacpZtuS5mWuXPqxFuK27yR+16Pf/7dn+jkjgaM+to9RSUSRQjsapxK/yVGaJfNHcZlzkk35iUX1YaYJjKqDIKAM+u5A4D+0UFz/h6631+Ze4miuJjtXJPNcG+B6IKceQL0bmTfx07weYMn7KAG7K/b368F6j87A4WzZA3cUWvP5yHaqw69V7/2GxXCF3izmlix8YshJwxRd3FxU+TOdFaullL0G9gVZGERSpLIX2lfuSBAJVFEbJ+QLZ+n7mS8mzCDTkZ+m5itIBEgHavKXsdwCZJxMPypUXTJN4pukW+ytc2k=
  - secure: Y/IKMT032YoBCLIkZ8hDOXxXLrLcQ401Kd57si5ts5++7HxszCIVP/b8jILWVwjPXyfxU3qdbkgGKQ72ir3Oonq720m7RLDvs07+F+VE0lu1YOV9tQlY80iWruHZnAMQirma63/TfgirDTisgzjcrvvAYcI8hVGQHojupZe6lebJ8pkUmnmVo+QukaM7CzNybe2cwyiGHMc0Jad7UkyWk1akkuywvwcBMdwc3GXg7DOpJ2vgwEpnSKHqxdgdOm5IzlBxG4cxHRs4VV7g0/o6O76cV9jaqv1wzTWIW5pct0XJ1NSmLKFPlOnbzlh+Gf6cghvcXP4DOXVuibVLteEZbD44Fx8gUDSTbR1fLY3iXmvpWJ4rojh/oSIn4XTfenIdVTfb9Bn+JfvWnHhAmhR76tLE5WhOMUGehAR3XGEyybZeqcb5Wvb1dJih7ui6+oy5EAGekymeJlOfRdO7gMmTVYobeBG2FN4KZ8J+Y7ZSfRRHskv2DFxvJBo8nkEgGoVF2EHsmGMtwqMh/jsgB3iCEyjLSUpZwN6N4q67N4ZnNU8CO3K5bjvKtNJmtkNZYyfN5B50bydjTK1M2OZndrp6YjVPfjp41m67E2EfCx60199wCxH8LQOflMI5YdR0U/bG6KfjbVEYbUitRguljJTfXJ3YudPpwbsTfGiysLd3vnE=

script:
- mvn clean deploy --settings travis-maven-settings.xml
