language: java

jdk:
- oraclejdk8

cache:
  directories:
  - "$HOME/.m2/repository"

env:
  global:
  - secure: d3WVDua8Qnrn6hGLAYuYbtzbPwt/5znZdxTSOpZ6EpnOEMjfakMBS8iSoMLwTyrpr1EPuUg5aIvry+cwnA3s8W4SCsgYXkSIJ7ogpja3LsIwk4eAEUnyDWPKch93Hngpn7FuoQCn5iZsqKpNhIf0xmimDVD8Cj4QFU9MwKhW+IEs2LwhKyUL2gAyiZOWzihEp0QA7X3mbovI8c/+RUOKMVa1I2OuX8yzsveu8BvJEZOWgav4ETxOKyS89XZiwCQSCrCFpVU+psLkIcM0yRs7uzT078YO65Wjwjtmc9tzoV2wzECB53H2cTL4iDcvivTvEtVNopn65dwySqcbWvTo33CbBJGnKlyDrQva44/6zoZOEyi2ZIZ+ljnWNjlSKtV7d35jY1ao2tIb5TGHr/lXqsqAOTPnYolbPUgeHhKRFwdDUIGXc2gQIxmOWB1hmFZusXs56r+8f4YeCENdprhwdflP7mQHox7KwCQXuAr8mzAs93W+RIzJQZBGEmCc/yDb7hNbSveimHlGEUtuHxH+wtfZOq/gPTpQRorMJ6GYpdT08TAANP++rPxqPrCQ17Tf+KNxZyVhkUDvxVZVkVsT+aln/zOzTavRLZ25IjFKlQSe2R0yMyEOR4kkGZL2SwpDjlCYSIHozT/2UQvlYEJfU4onMY6PGnFT0UhaeHCPHrY=
  - secure: lSlWF4S3Zv+ESs7r48+p+f7a/bGgvnWa24CIFuOh3Suyn2X7347hGsqQLuJYm/SgfLbvqAs6mgs1krXftwny5bq8hhVo+QqnDRUdAUecg7IdGWH6ekjS18DJvRFWEDBW6gVMCSds+icd5n1UR8h2ivXmEsK2cCYauAWkl9EZN08gNFQG3vs9aRcU/87yaFgthsZA+kxmo47ACoZ4acQZUT62IYSGJGGCLGDgPXmxwcOaN5GcKtzdtDYJbcc1/zawkwS6napDh74mN8QeF2Hs9w9Z87VL4wTcfilrjyso9pEmyKSZCaihDeQngC3I/vNmYfZabmu6q5rpORD5TLmBLOFa2+44XFjC2qv2Ni7eKSgm6FqsLRRxi5LAcHv6sYctCAFzjImSD1kAm9glq1xn/uGoP1mX6A3Gnnh38YB4MYLZBxJQoQVRR/2WAfEQGrwc7Vvqdp+CRTN8c4EExIYmXkRgXZn0eyo5PPx2WUsz9jE73RuKw8Tsg2C9BXgTKg1HTwQzmJ5zFkyj+B87Kn77CIfE8fMzxwIROMy5qJX6/M6061Ckx+ncIvxexFYX1LO3HFwLoJE3AmeqW6CxAwCxxs8WR2tTuZzuIVfTTGZwVI0xXLnsVu/YM7P0R7icOF+n+XWq+JrtCk3Oco/7VhjOoB+tEJJo5OvwSqc5fPjx9ac=

script:
- mvn clean deploy --settings travis-maven-settings.xml
